version: "3.8"

services:
  # ---------------------------------------------------------
  # 1. CMS APPLICATION (PHP-FPM)
  # ---------------------------------------------------------
  cms_app:
    build:
      context: .
      target: fpm_app # Mengeksekusi STAGE 1 dari Dockerfile
    image: rs-elisabeth-cms-app:latest
    container_name: rses_cms_app
    restart: always
    env_file:
      - .env
    environment:
      # Override DB_HOST agar connect ke container rses_cms_db (bukan localhost)
      - DB_HOST=rses_cms_db

    networks:
      - rses_cms_network
    depends_on:
      - rses_cms_db

  # ---------------------------------------------------------
  # 2. NGINX (Web Server)
  # ---------------------------------------------------------
  cms_nginx:
    build:
      context: .
      target: web_server # Mengeksekusi STAGE 2 dari Dockerfile
    image: rs-elisabeth-cms-nginx:latest
    container_name: rses_cms_nginx
    restart: always
    ports:
      - "2302:80" # Mapping port 2302 di server mengarah ke port 80 di container Nginx
    networks:
      - rses_cms_network
    depends_on:
      - cms_app

  # ---------------------------------------------------------
  # 3. DATABASE POSTGRESQL (Opsional)
  # ---------------------------------------------------------
  rses_cms_db:
    image: postgres:15-alpine
    container_name: rse_rses_cms_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - rses_cms_db_data:/var/lib/postgresql/data
    networks:
      - rses_cms_network

networks:
  rses_cms_network:
    driver: bridge

volumes:
  rses_cms_db_data:
